import { buttonVariants } from '@/components/ui/button';

export const learnerAccountStyles = {
  profileLead: 'flex flex-col gap-5 rounded-xl border bg-card p-6 sm:flex-row sm:items-center',
  avatarWrap: 'shrink-0',
  avatar: 'size-24 rounded-full border object-cover',
  avatarFallback: 'flex size-24 items-center justify-center rounded-full bg-primary text-3xl font-bold text-primary-foreground',
  profileIdentity: 'min-w-0',
  sectionLabel: 'text-xs font-semibold uppercase tracking-[0.2em] text-primary',
  summary: 'grid gap-3 sm:grid-cols-3 [&_div]:rounded-lg [&_div]:border [&_div]:bg-card [&_div]:p-4 [&_span]:block [&_span]:text-sm [&_span]:text-muted-foreground [&_strong]:mt-1 [&_strong]:block',
  profileStats: 'mt-5',
  formSection: 'mt-8 rounded-xl border bg-card p-6',
  formGrid: 'grid gap-5',
  message: 'rounded-lg border p-3 text-sm',
  messageSuccess: 'border-emerald-500/30 bg-emerald-500/5 text-emerald-700',
  messageError: 'border-destructive/30 bg-destructive/5 text-destructive',
  field: 'grid gap-2',
  fieldHint: 'text-sm leading-6 text-muted-foreground',
  formActions: 'flex flex-wrap gap-3 pt-2',
  settingsSection: 'mb-6 rounded-xl border bg-card p-6',
  settingRow: 'mt-4 flex items-center justify-between gap-4 rounded-lg border bg-background p-4 transition hover:border-primary/40 hover:bg-muted/40',
  settingCopy: 'grid gap-1 text-left [&_strong]:font-semibold [&_span]:text-sm [&_span]:text-muted-foreground',
  settingMarker: 'shrink-0 text-xs font-semibold text-primary',
  oauthRow: 'flex items-center justify-between gap-4 rounded-lg border bg-muted/30 p-4',
  oauthBadge: 'rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary',
  toggle: 'flex w-full items-center justify-between gap-4 rounded-lg border bg-background p-4 transition hover:border-primary/40 hover:bg-muted/40',
  passwordPanel: 'mt-4 rounded-lg border bg-muted/20 p-5',
  passwordField: 'relative [&_input]:pr-11',
  iconButton: 'absolute right-1 top-1/2 flex size-8 -translate-y-1/2 items-center justify-center rounded-md text-muted-foreground hover:bg-muted hover:text-foreground',
  strength: 'grid gap-2',
  strengthBars: 'grid grid-cols-4 gap-1 [&_span]:h-1.5 [&_span]:rounded-full [&_span]:bg-muted',
  strengthLabel: 'text-xs font-medium',
  strengthStrong: 'text-emerald-700 [&_span]:!bg-emerald-500',
  strengthMedium: 'text-amber-700 [&_span]:!bg-amber-500',
  strengthWeak: 'text-destructive [&_span]:!bg-destructive',
  state: 'rounded-xl border border-dashed bg-card p-8 text-center',
  stateInner: 'mx-auto grid max-w-md justify-items-center gap-3',
  stateCode: 'text-xs font-semibold uppercase tracking-[0.2em] text-primary',
  loadingBar: 'h-2 w-full max-w-xs animate-pulse rounded-full bg-muted',
  primaryAction: buttonVariants(),
  secondaryAction: buttonVariants({ variant: 'outline' }),
  sectionHead: 'mb-5 flex flex-wrap items-end justify-between gap-3',
  sectionNote: 'text-sm text-muted-foreground',
  records: 'grid gap-3',
  record: 'grid gap-4 rounded-xl border bg-card p-5 sm:grid-cols-[2.5rem_minmax(0,1fr)_auto_auto] sm:items-center',
  certificateRecord: 'sm:grid-cols-[2.5rem_minmax(0,1fr)_auto]',
  recordIndex: 'text-xs font-semibold text-muted-foreground',
  recordTitle: 'font-semibold',
  recordMeta: 'mt-1 flex flex-wrap gap-x-3 gap-y-1 text-sm text-muted-foreground',
  recordCode: 'font-mono text-xs',
  amount: 'font-semibold',
  status: 'w-fit rounded-full px-2.5 py-1 text-xs font-semibold',
  statusSuccess: 'bg-emerald-500/10 text-emerald-700',
  statusPending: 'bg-amber-500/10 text-amber-700',
  statusInfo: 'bg-sky-500/10 text-sky-700',
  statusDanger: 'bg-destructive/10 text-destructive',
  actions: 'flex flex-wrap gap-2',
} as const;
