import MainContent from '@/components/layout/MainContent';
import Footer from '@/components/layout/Footer';
import Navbar from '@/components/layout/Navbar';
import { Card, CardContent } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';

export function CatalogRouteSkeleton({ label = 'กำลังโหลดรายการ' }: { label?: string }) {
  return <><Navbar /><MainContent className="min-h-screen bg-muted/20" aria-busy="true" aria-label={label}><header className="border-b bg-background"><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><Skeleton className="h-4 w-32" /><Skeleton className="mt-4 h-12 w-[36rem] max-w-full" /><Skeleton className="mt-4 h-5 w-[30rem] max-w-full" /></div></header><section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><Card className="mb-8"><CardContent className="grid gap-3 p-4 md:grid-cols-[minmax(0,1fr)_12rem_12rem_auto]"><Skeleton className="h-10 w-full" /><Skeleton className="h-10 w-full" /><Skeleton className="h-10 w-full" /><Skeleton className="h-10 w-24" /></CardContent></Card><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{[1,2,3,4,5,6].map(item=><Card className="overflow-hidden" key={item}><Skeleton className="aspect-video w-full rounded-none" /><CardContent className="grid gap-4 p-5"><Skeleton className="h-5 w-24" /><Skeleton className="h-7 w-full" /><Skeleton className="h-4 w-full" /><Skeleton className="h-9 w-full" /></CardContent></Card>)}</div></section></MainContent><Footer /></>;
}

export function ArticleRouteSkeleton() {
  return <><Navbar /><MainContent className="min-h-screen bg-background" aria-busy="true" aria-label="กำลังโหลดบทความ"><header className="border-b bg-muted/30"><div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8"><Skeleton className="h-4 w-52" /><Skeleton className="mt-5 h-12 w-full" /><Skeleton className="mt-3 h-12 w-3/4" /><Skeleton className="mt-5 h-5 w-80 max-w-full" /></div></header><div className="mx-auto grid max-w-7xl gap-10 px-4 py-10 sm:px-6 lg:grid-cols-[minmax(0,1fr)_16rem] lg:px-8"><article className="grid gap-5"><Skeleton className="aspect-[16/8] w-full" />{[1,2,3,4,5,6].map(item=><Skeleton className={item % 3 === 0 ? 'h-5 w-3/4' : 'h-5 w-full'} key={item} />)}</article><Card className="h-fit"><CardContent className="grid gap-4 p-5"><Skeleton className="h-5 w-28" /><Skeleton className="h-4 w-full" /><Skeleton className="h-4 w-5/6" /><Skeleton className="h-4 w-4/6" /></CardContent></Card></div></MainContent><Footer /></>;
}

export function ProofRouteSkeleton({ label = 'กำลังตรวจสอบรายการ' }: { label?: string }) {
  return <><Navbar /><MainContent className="min-h-screen bg-muted/20 py-10" aria-busy="true" aria-label={label}><div className="mx-auto max-w-5xl px-4 sm:px-6"><Skeleton className="h-4 w-36" /><Skeleton className="mt-4 h-12 w-[36rem] max-w-full" /><Skeleton className="mt-4 h-5 w-[28rem] max-w-full" /><div className="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_20rem]"><Card><Skeleton className="aspect-[16/8] w-full rounded-none" /><CardContent className="grid gap-4 p-6"><Skeleton className="h-7 w-3/4" /><Skeleton className="h-5 w-32" /><Skeleton className="h-20 w-full" /></CardContent></Card><Card className="h-fit"><CardContent className="grid gap-4 p-6"><Skeleton className="h-6 w-28" /><Skeleton className="h-8 w-full" /><Skeleton className="h-16 w-full" /><Skeleton className="h-10 w-full" /></CardContent></Card></div></div></MainContent><Footer /></>;
}
